environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      CONDA_PY: "27"
      PYTHON_ARCH: "32"

    - PYTHON_VERSION: "2.7"
      CONDA_PY: "27"
      PYTHON_ARCH: "64"

    - PYTHON_VERSION: "3.4"
      CONDA_PY: "34"
      PYTHON_ARCH: "32"

    - PYTHON_VERSION: "3.4"
      CONDA_PY: "34"
      PYTHON_ARCH: "64"

    - PYTHON_VERSION: "3.5"
      CONDA_PY: "35"
      PYTHON_ARCH: "32"

    - PYTHON_VERSION: "3.5"
      CONDA_PY: "35"
      PYTHON_ARCH: "64"

install:
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda create -n testenv --yes --quiet python=%PYTHON_VERSION% numpy scipy nose
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - git submodule update --init --recursive
  - python setup.py install

test_script:
  - cd test
  - nosetests

