os:
  - linux
  - osx
language: python
env:
  - PYTHON_VERSION="2.6"
  - PYTHON_VERSION="2.7"
  - PYTHON_VERSION="3.3"
  - PYTHON_VERSION="3.4"
install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON_VERSION numpy scipy nose argparse
  - source activate test-environment
  - conda install -c https://conda.anaconda.org/cyclus lapack
  - python setup.py install

script:
  - cd test && nosetests test_scs_basic.py test_scs_rand.py test_scs_sdp.py

notifications:
  email:
    - bodonoghue85@gmail.com

