os:
  - linux
  - osx

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install numpy scipy
  - python setup.py install

script:
  - cd test && nosetests test_scs_basic.py test_scs_rand.py test_scs_sdp.py

notifications:
  email:
    - bodonoghue85@gmail.com

